default: &default
  database: steemit
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost
  port: 3306

development:
  <<: *default
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  
test:
  <<: *default
  database: admin_test

production:
  <<: *default
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  port: <%= ENV['MYSQL_PORT'] %>
